# Generated by Django 5.0.4 on 2024-04-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masark', '0003_alter_station_id_alter_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ID',
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
